#!/usr/bin/env bash

Green="\033[32m"
Red="\033[31m"
Yellow='\033[33m'
Font="\033[0m"
INFO="[${Green}INFO${Font}]"
ERROR="[${Red}ERROR${Font}]"
WARN="[${Yellow}WARN${Font}]"
INFO(){
echo -e "${INFO} ${1}"
}
ERROR(){
echo -e "${ERROR} ${1}"
}
WARN(){
echo -e "${WARN} ${1}"
}

MODELS=$1
INSTALL_SOURCE=$2
INIT=$3

if [ "$(fdisk -l)" != "" ]; then
    ERROR "请在容器内执行本脚本"
    exit 1
fi

if [[ "${INIT}" = "yes" || "${INIT}" = "true" ]]; then
    if [ -d /config/plugins/whisper.cpp ]; then
        INFO "whisper.cpp 以安装"
        exit 0
    fi
fi

if [[ "${INSTALL_SOURCE}" = 'cn' || "${INSTALL_SOURCE}" = 'CN' ]]; then
    whisper_cpp_url=https://ghproxy.com/https://github.com/ggerganov/whisper.cpp.git
    sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_MIRROR}/g" /etc/apk/repositories
    apk update -f
else
    whisper_cpp_url=https://github.com/ggerganov/whisper.cpp.git
fi

if [ "${MODELS}" = "" ]; then
    WARN "未指定模型 ，默认使用 small 模型"
    MODELS="small"
fi

INFO "开始编译安装 whisper.cpp"
INFO "下载 whisper.cpp 源码"
if [ -d /config/plugins/whisper.cpp ]; then
    ERROR "/config/plugins/whisper.cpp 目录已存在，请清除后重新执行脚本。"
    exit 1
else 
    mkdir -p /config/plugins/whisper.cpp
fi
git clone -b master ${whisper_cpp_url} /config/plugins/whisper.cpp --depth=1
if [ $? -ne 0 ]; then
    ERROR "whisper.cpp 源码下载失败"
    exit 1
else
    INFO "whisper.cpp 源码下载成功"
    INFO "安装编译软件包"
    sudo apk add --no-cache build-base sdl2-dev alsa-utils
    if [ $? -ne 0 ]; then
        ERROR "编译软件包安装失败"
        exit 1
    else
        INFO "编译软件包安装成功"
        INFO "开始编译"
        cd /config/plugins/whisper.cpp
        echo "CFLAGS += -D_POSIX_C_SOURCE=199309L" > Makefile.NT
        make -f Makefile -f Makefile.NT
        if [ $? -ne 0 ]; then
            ERROR "whisper.cpp 编译安装失败"
            exit 1
        else
            INFO "whisper.cpp 编译安装成功"
            INFO "开始下载 models"
            bash ./models/download-ggml-model.sh ${MODELS}
            if [ $? -ne 0 ]; then
                ERROR "models 下载失败"
                exit 1
            else
                INFO "models 下载成功"
                INFO "whisper.cpp 路径: /config/plugins/whisper.cpp/main"
                models_dir=$(ls models/ggml*)
                INFO "whisper.cpp 模型路径: /config/plugins/whisper.cpp/${models_dir}"
                INFO "安装完成！"
                exit 0
            fi
        fi
    fi
fi

